apiVersion: v1
kind: Secret
metadata:
  name: qa-api-secrets
  labels:
    app: qa-api
type: Opaque
data:
  MONGO_URI: <base64-ile-encode-edilmis-mongo-uri>
  JWT_SECRET_KEY: <base64-ile-encode-edilmis-jwt-secret>
  SMTP_USER: <base64-ile-encode-edilmis-smtp-user>
  SMTP_APP_PASS: <base64-ile-encode-edilmis-smtp-pass>
  # Diğer secret/env değerlerini de ekleyebilirsin 